### ISSUE TITLE
Add a full 100vh background image to the app

### ISSUE THREAD

**Issue by Halim-Shams** [Halim-Shams/todo-list#1]
It'll better to add a full "100vh" image to the background, It must a random image every time the page refreshes.

**Options:**
1. You can use the Unsplash random URL to get a random image every time by refreshing the page.
To get a random image, you can use this URL `https://source.unsplash.com/random`
![React App - Google Chrome 11_1_2022 9_42_02 AM](https://user-images.githubusercontent.com/96909515/199167847-c25e1f66-ff0e-49d1-bac2-9231ec86b08f.png)

**Comment by sahilm-10** [comment]
Can you assign this issue to me ? New to Open-Source

**Comment by Halim-Shams** [comment]
@sahilm-10 sure, go ahead.

**Comment by Halim-Shams** [comment]
@sahilm-10  I am unassigning you because you didn't able to pr!
