### ISSUE TITLE
Add a full 100vh background image to the app

### ISSUE THREAD

**Issue by Halim-Shams** [Halim-Shams/todo-list#2]
It'll better to add a full "100vh" image to the background using Tailwindcss, It must a random image every time the page refreshes.

Options:

You can use the Unsplash random URL to get a random image every time by refreshing the page.
To get a random image, you can use this URL https://source.unsplash.com/random
![React App - Google Chrome 11_1_2022 9_42_02 AM](https://user-images.githubusercontent.com/96909515/199506766-97bf47d6-1cd1-4806-a933-4b92664aabb7.png)

**Comment by Rishi6229** [comment]
Hi , can anyone explain me Im new to open source and I am willing to contribute here.

**Comment by Faizan59khan** [comment]
Hey @Halim-Shams can u assign this to me

**Comment by Halim-Shams** [comment]
Sure you both (@Rishi6229  and @Faizan59khan) can work on this, I'll merge the pr which is sooner and better.

**Comment by chwasifjameel** [comment]
Hi @Halim-Shams I made a fix. Please check my PR.

https://github.com/Halim-Shams/todo-list/pull/4

**Comment by Halim-Shams** [comment]
#4
